package raf.draft.dsw.controller.logger;

public enum ErrorType {
    NODE_CANNOT_BE_DELETED, NAME_CANNOT_BE_EMPTY, NAME_OF_NODE_ALREADY_EXISTS, NODE_NOT_SELECTED, PROJECTEXPLORER_CANNOT_BE_DELETED,
    NODE_CANNOT_HAVE_CHILDREN
}
